In [90]:
import numpy as np

# Task 1

In [11]:
intarray = np.array([1, 2, 3], dtype=np.dtype('i4'))          # 4 Byte Integer array
floatarray = np.array([1, 2, 3], dtype=np.dtype('f8'))        # 8 Byte Float array 
chararray = np.array(["a", "b", "c"], dtype=np.dtype('U2'))    # 2 Bit String array 

In [12]:
print("Shape of int array: ", intarray.shape, " DType of int array: ", intarray.dtype)
print("Shape of flaot array: ", floatarray.shape, " DType of float array: ", floatarray.dtype)
print("Shape of char array: ", chararray.shape, " DType of char array: ", chararray.dtype)

Shape of int array:  (3,)  DType of int array:  int32
Shape of flaot array:  (3,)  DType of float array:  float64
Shape of char array:  (3,)  DType of char array:  <U2


# Task 2

In [13]:
zerosarray = np.zeros((3,)) 
emptyarray = np.empty((3,))
identityarray = np.identity(3)
eyearray = np.eye(3)
fullarray = np.full((3,), 69)

# Task 3

In [16]:
objarray = np.array(["a", "b", "c"], dtype=np.dtype("O"))

In [17]:
objarray.dtype

dtype('O')

# Task 4

In [18]:
equa5array = np.linspace(5, 15, 5)

In [19]:
equa5array.shape

(5,)

In [20]:
equa5array

array([ 5. ,  7.5, 10. , 12.5, 15. ])

# Task 5

In [25]:
rangedarray = np.arange(100) + 1 

In [26]:
rangedarray

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

# Task 6

In [27]:
rangedarray.reshape((100 ,15))

ValueError: cannot reshape array of size 100 into shape (100,15)

In [28]:
# Not Possible

# Task 7

In [29]:
rangedarray.reshape((100 ,10))

ValueError: cannot reshape array of size 100 into shape (100,10)

In [30]:
# Not Possible

# Task 8

In [31]:
reshapedrangedarray = rangedarray.reshape((50, 2))

In [32]:
reshapedrangedarray.ravel()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [33]:
reshapedrangedarray.flatten()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [34]:
# Both work same if there is just one dimesion to flatten

# Task 9

In [35]:
summingarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [36]:
summingarray.sum(axis=0)

array([12, 15, 18])

In [37]:
summingarray.sum(axis=1)

array([ 6, 15, 24])

# Task 10

In [38]:
summingarray.nbytes

36

# Task 11

In [41]:
onedarray = np.array([2, 3, 4, 5, 6, 90, 45, 24])

In [43]:
onedarray[onedarray.argmax()]

90

# Task 12

In [45]:
twodarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [46]:
twodarray.max()

9

# Task 13

In [50]:
tosortarray = np.array([2, 3, 4, 5, 6, 90, 45, 24])

In [51]:
tosortarray[tosortarray.argsort(kind = "heapsort")]

array([ 2,  3,  4,  5,  6, 24, 45, 90])

# Task 14

In [52]:
muller = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mulland = np.array([[9, 8, 7], [6, 1, 2], [5, 4, 3]])

In [53]:
muller * mulland

array([[ 9, 16, 21],
       [24,  5, 12],
       [35, 32, 27]])

In [54]:
np.multiply(muller, mulland)

array([[ 9, 16, 21],
       [24,  5, 12],
       [35, 32, 27]])

In [55]:
np.dot(muller, mulland)

array([[ 36,  22,  20],
       [ 96,  61,  56],
       [156, 100,  92]])

"*" and np.multiply() do element-wise multiplication, whereas np.dot() does scalar multiplication

# Task 15

In [56]:
tosqrtarray = np.array([2, 3, 4, 5, 6, 90, 45, 24])

In [57]:
np.sqrt(tosqrtarray)

array([1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974,
       9.48683298, 6.70820393, 4.89897949])

In [58]:
tonormarray = np.array([2, 3, 4, 5, 6, 90, 45, 24])

In [59]:
np.linalg.norm(tonormarray)

103.87973815908471

# Task 16

In [60]:
tostdarray = np.array([2, 3, 4, 5, 6, 90, 45, 24, 0, 0, 25, 45])

In [61]:
np.std(tostdarray)

26.258728707485695

In [62]:
tozeroarray = np.array([2, 3, 4, 5, 6, 90, 45, 24, 0, 0, 25, 45])

In [63]:
zeromask = tozeroarray == 0
tozeroarray[zeromask]

array([0, 0])

In [64]:
nonzeromask = tozeroarray != 0
tozeroarray[nonzeromask]

array([ 2,  3,  4,  5,  6, 90, 45, 24, 25, 45])

In [65]:
tomeanarray = np.array([2, 3, 4, 5, 6, 90, 45, 24, 0, 0, 25, 45])

In [66]:
np.mean(tomeanarray)

20.75

# Task 17

In [72]:
toradarray = np.array([0, 90, 180, 270, 360])

In [73]:
radarray = (toradarray * 2 * np.pi) / (360)
radarray

array([0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531])

In [74]:
todegarray = np.array([0, np.pi/2, np.pi, 3 * np.pi / 2, 2 * np.pi])

In [75]:
degarray = (todegarray * 360) / (2 * np.pi)
degarray

array([  0.,  90., 180., 270., 360.])

# Task 18

In [77]:
np.save("./RadArray", radarray)

In [80]:
loadedradarray = np.load("./RadArray.npy")

In [81]:
loadedradarray

array([0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531])

# Task 19

In [82]:
mu, sigma = 21, 4.5 # mean and standard deviation
s = np.random.normal(mu, sigma, size=((3,3,12,3)))

In [85]:
s.mean()

21.104405496809964

In [87]:
s.std()

4.742596094053223

In [88]:
s.var()

22.492217711328887

In [89]:
s.min()

6.353468672201824